---
language:
  - c
  - c++
sudo: false
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script:
  - CC=$CC CXX=$CXX cmake .
  - make -j4
  - ./SMHasher falkhash --test=Speed,Avalanche,Zeroes,Seed
