---
language:
  - c++
sudo: false
env:
  matrix:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

script:
  - CC=$CC CXX=$CXX cmake .
  - make -j4
  - ./SMHasher --test=Speed,Avalanche,Zeroes,Seed falkhash
